### PR TITLE
Some performance improvements

### PR DESCRIPTION
**Pull request by dselivanov**
see commit messages

### CODE REVIEW

**Comment by ocourtin** [comment]
Hi Dmitriy !

Thanks for this PR.
Did you perform some (quick) performance bench on it ?

**Comment by dselivanov** [comment]
In current case it is ~5-7%. But I've observed cases when it is much higher. I found disabling threading is particularly useful when using torch multiprocess data loaders.

**Comment by dselivanov** [comment]
Also note that latest commit brings back png, wepb, jpeg reading with PIL. Your latest changes caused incorrect data loading (I found it as `rs compare` stopped work)

**Comment by ocourtin** [comment]
Thanks Dmitryi for this regression report. Just fixed.

On the performance improvments, on the other side, i'm still unable to reproduce any significative results, on training. Looks like i'm more benching some inner cache ^^

Feel free to push more information on your own way to reproduce it, and about the kind of hardware you use.


On a more broader comment, i believe more in our ability to significantly enhance performances with #82 and #10

**Comment by dselivanov** [comment]
I run all the experiments on nvidia DGX-2. Reported performance improvement is for spacenet dataset and building detection.

**Comment by ocourtin** [comment]
@dselivanov 
I've implemented a first DDP support for Training, cf #82 
It allows real performance scaling with MultiGPU.
You should give a try...

I've just try again both `pin_memory` and `cv2.setNumThreads(1)`
but can't find any significant perf improvment, so close this PR.

Next step on this topic will be #10

**Pull request closed without merging**
